### PR TITLE
Bump bench.ts version

### PR DESCRIPTION
**Pull request by seishun**
0.66.0 errors on TypeScript 4.0.

### CODE REVIEW

**Comment by seishun** [comment]
Should I fix fmt as part of this PR?

**Comment by keithamus** [comment]
Please!

**Comment by seishun** [comment]
`deno fmt` updated files in testdata, which no longer match generator output. What would you suggest?

**Comment by keithamus** [comment]
Part of the guarantee of this project is I'd like it to generate files that pass `deno fmt`. We should adapt the generator to fix these failings. It looks like sort order has changed. Looks like the sort needs changing to use `localeCompare`:

 https://github.com/keithamus/deno-protod/blob/daec43844a2a5d84636d67b6f12a71a2cb5a8eb7/generate.ts#L294

```typescript
    for (const id of [...this.#imports].sort((a, b) => a.localeCompare(b)) yield `  ${id},`;
```

**Review by keithamus — APPROVED** [review]
Great! Thanks for doing this! :+1:

**Pull request merged**
